language: php
sudo: false
services:
- mysql
cache:
  directories:
  - "$HOME/.composer/cache/files"
matrix:
  fast_finish: true
  include:
  - php: 7.1
env:
- SYMFONY_VERSION="4.0.*" DB=mysql
before-install:
- composer self-update
install:
- cp .env.travis.dist .env
- composer install
- php bin/console doctrine:database:create --env=test
- php bin/console doctrine:schema:create --env=test
notifications:
email: nicks03@hotmail.co.uk
deploy:
  provider: heroku
  api_key: 96f058fd-0efa-45d4-b420-bfc64eaf0e2e
    secure: S/VhDPw0W+BxnbKBb+9M3AcyGebCF8tv3P7HfPfVhtQT4Zz7zAcoxNCJJzZ0+rEJJRfdGuilJwKyBeKp2lo8CAP5mi7BJsnq69AoqDcDtISGHoVWMHkprKe5v1TgNLFvE3V+/xjwxfXbDnYABjsuHyeMdVxa15qUKXuoSi2xhBQ+30gOQDtvLvjnX2EJ1lRDdJPlSvlqgU60QHxcdh3HRk0JCgJYQpIbc+h+P7kBeDXOEWZmJtb6wBE7bdK0LNW5lC4sNpuwk/ZLrlHfomGN7lTm8/w9Ss/AaL1TDAf8oxtekK2DaRaIY8/+8ZlZIbHorVE0FVwmUm5v2K64t95xy0EgIy5mj4XkaAWot1cd1/zHoAMO8HChXctziqulvl/jWI3ruYxELxWarGoJqQOYzpozjfoOsATpzF1jJvM4vU2hDsWpHPZMNPBS6mrkzH2U3JPIRHRmHojb+3LCTLoHnzLWu5A2lgF6kEX8lV8/+zz9gFrfiBYkUYp1DNOWuyggUTwWEdurq01eRqmL8esCM/BmT8FedJsgASR2Rp9678Di1yDNDXCjv10PYs0Nlt25mW0YGh5JLTy8dX1ui3uifnYyXXYx7zCgClY/B6odgaGGtzLASLAbZKIelJNmu95hZ+gsXHssZjLifi19JzEuT+IuZZfVif9zfXNSmoBu+hY=
  app: rblog3
